---
- debug: var=ansible_os_family

- include: install.deb.yml
  when: ansible_os_family == 'Debian'
  tags: [installation]

- include: configure.yml
  tags: [configuration]

#- include: grafana.yml
#  tags: [grafana, configuration]

- include: dht22.yml
  when: ansible_lsb.id == 'Raspbian'
  tags: [dht]

