---
# vars file for pirest-sense-hat




### APP Configuration
app_name: "pirest-sense-hat"
app_src: "../src/"
# The path where pirest-sense-hat will be downloaded and installed.
app_path: "/opt/pirest_sense_hat"
app_statics: "{{ app_path }}/collect_statics"
app_user: root
app_group: root
app_port: 8000
app_dir_logs: "/var/log/{{ app_name }}"

### NGINX Configuration
nginx_remove_default_vhost: true
nginx_sites_available: /etc/nginx/sites-available
nginx_sites_enabled: /etc/nginx/sites-enabled

### Values for dht22 sensor (pi_attach == 'dht22')
dht22_library_path: "/opt/adafruit_python_dht"
dht22_library_git: "https://github.com/adafruit/Adafruit_Python_DHT.git"


